### ISSUE TITLE
Add generated Cloud Datastore protos

### ISSUE THREAD

**Issue by pcostell** [googleapis/proto-client-go#3]
Can we have the Cloud Datastore v1beta3 protos added here as well?

**Comment by saicheems** [comment]
I'll generate them today

**Comment by saicheems** [comment]
Actually ran into an issue with the naming of the `type` package... I'll check with some folks to see what to do there. Type is a reserved keyword, so protoc fails to generate anything in that package.

**Comment by saicheems** [comment]
Sorry for the wait, we're transitioning generated protos to another repo under the google org. Assigning Michael - please close/update this bug when that transition is complete.

**Comment by saicheems** [comment]
We've moved everything to a new repo, done here:
https://github.com/google/go-genproto
